Repository NerdyNomads/Text-Savvy, pull requests merged in 2022-02, with the labels that each got.

#28 Updated readme with the project objective
  readme.md
Labels: documentation

#27 Updated readme information to describe current project
  readme.md
Labels: documentation

#29 Link wiki
  img/COMP 4350_ Architecture.jpg
  readme.md
Labels: documentation

#30 Add more details on core features section
  readme.md
Labels: documentation

#31 Added tools and tech link in Read Me
  readme.md
Labels: documentation

#32 Sprint 1
  COMP_4350_Architecture.png
  readme.md
Labels: documentation

#47 Setup Auth0 with React App
  web-app/.gitignore
  web-app/package-lock.json
  web-app/package.json
  web-app/src/App.js
  web-app/src/components/LoginButton.js
  web-app/src/components/LogoutButton.js
  web-app/src/components/Profile.js
  web-app/src/index.js
Labels: high priority, front-end

#48 Fixed App.js error
  .gitignore
  web-app/src/App.js
Labels: bug

#51 Setup front end for Main screen
  web-app/src/App.css
  web-app/src/App.js
  web-app/src/components/Profile.js
  web-app/src/components/Sidebar.css
  web-app/src/components/Sidebar.js
  web-app/src/components/TextBox.css
  web-app/src/components/TextBox.js
  web-app/src/components/TextList.css
  web-app/src/components/TextList.js
Labels: medium priority, front-end

#43 Set up ESLint
  web-app/.eslintrc.yml
  web-app/README.md
  web-app/package-lock.json
  web-app/src/App.js
Labels: medium priority, front-end

#50 Setup MongoDB connection
  web_app/text_savvy_backend/.gitignore
  web_app/text_savvy_backend/README.md
  web_app/text_savvy_backend/package-lock.json
  web_app/text_savvy_backend/package.json
  web_app/text_savvy_backend/server.js
Labels: high priority, back-end

#55 Changed frontend and backend directories
  back-end/.gitignore
  back-end/README.md
  back-end/objects/workspace.js
  back-end/package-lock.json
  back-end/package.json
  back-end/server.js
  front-end/.eslintrc.yml
  front-end/.gitignore
  front-end/README.md
  front-end/package-lock.json
  front-end/package.json
  front-end/public/Text Savvy Logo.png
  front-end/public/eventPage.js
  front-end/public/favicon.ico
  front-end/public/index.html
  front-end/public/logo192.png
  front-end/public/logo512.png
  front-end/public/manifest.json
  front-end/public/robots.txt
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/App.test.js
  front-end/src/components/LoginButton.js
  front-end/src/components/LogoutButton.js
  front-end/src/components/Sidebar.css
  front-end/src/components/Sidebar.js
  front-end/src/components/TextBox.css
  front-end/src/components/TextBox.js
  front-end/src/components/TextList.css
  front-end/src/components/TextList.js
  front-end/src/index.css
  front-end/src/index.js
  front-end/src/logo.svg
  front-end/src/reportWebVitals.js
  front-end/src/setupTests.js
  web-app/package-lock.json
  web_app/.env
  web_app/text_savvy_backend/package-lock.json
Labels: medium priority, front-end, back-end

#56 Browser extension working with saving data to backend database
  back-end/persistence/accounts.js
  back-end/persistence/models/accounts.model.js
  back-end/persistence/models/texts.model.js
  back-end/persistence/models/workspaces.model.js
  back-end/persistence/texts.js
  back-end/persistence/workspaces.js
  back-end/presentation/test_ui.html
  back-end/server.js
  front-end/package.json
  front-end/public/eventPage.js
  front-end/public/manifest.json
  front-end/src/App.js
Labels: high priority, front-end, back-end, Chrome Extension
